In [225]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [226]:
call=pd.read_excel(r"C:\Users\ELCOT\OneDrive\New Folder\Call center perfomance analysis\Dataset\call_center.xlsx",header=2,usecols="B:H",)

In [227]:
call.head()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,Call_7271,C0003,NaN,R05,2023-01-01,128.0,4.9
1,Call_7272,C0004,119.0,R05,2023-01-01,135.0,2.9
2,Call_7273,C0005,68.0,R02,2023-01-01,66.0,4.7
3,Call_7274,C0014,119.0,R02,2023-01-01,NaN,2.9
4,Call_7275,C0011,NaN,R01,2023-01-02,31.0,2.8

In [228]:
customers=pd.read_excel(r"C:\Users\ELCOT\OneDrive\New Folder\Call center perfomance analysis\Dataset\call_center.xlsx",header=2,usecols="L:O",nrows=15)

In [229]:
customers

   Customer ID.1  Gedner  Age        City
0          C0001    Male   41    Columbus
1          C0002    Male   31   Cleveland
2          C0003    Male   26  Cincinnati
3          C0004    Male   36  Cincinnati
4          C0005    Male   37    Columbus
5          C0006    Male   23    Columbus
6          C0007  Female   22   Cleveland
7          C0008  Female   42   Cleveland
8          C0009  Female   25    Columbus
9          C0010  Female   30   Cleveland
10         C0011  Female   30  Cincinnati
11         C0012  Female   28  Cincinnati
12         C0013  Female   37   Cleveland
13         C0014  Female   38    Columbus
14         C0015  Female   43   Cleveland

In [230]:
customers.head()

  Customer ID.1 Gedner  Age        City
0         C0001   Male   41    Columbus
1         C0002   Male   31   Cleveland
2         C0003   Male   26  Cincinnati
3         C0004   Male   36  Cincinnati
4         C0005   Male   37    Columbus

In [231]:
call.tail()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
995,Call_8266,C0002,81.0,R05,2023-12-30,28.0,3.9
996,Call_8267,C0007,127.0,R04,2023-12-30,215.0,3.8
997,Call_8268,C0013,146.0,R05,2023-12-31,115.0,2.3
998,Call_8269,C0010,123.0,R05,2023-12-31,64.0,3.7
999,Call_8270,C0009,114.0,R01,2023-12-31,40.0,3.9

In [232]:
call.sample(4)

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
953,Call_8224,C0004,149.0,R02,2023-12-03,42.0,3.3
809,Call_8080,C0005,87.0,R01,2023-10-08,23.0,4.2
90,Call_7361,C0015,84.0,R05,2023-02-04,195.0,4.1
383,Call_7654,C0014,60.0,R03,2023-04-19,84.0,4.8

In [233]:
type(call)
type(customers)

pandas.DataFrame

In [234]:
call.shape

(1000, 7)

In [235]:
customers.shape

(15, 4)

In [236]:
call.columns

Index(['Call number', 'Customer ID', 'Duration', 'Representative',
       'Date of Call', 'Purchase Amount', 'Satisfaction Rating'],
      dtype='str')

In [237]:
call.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call number          1000 non-null   str
 1   Customer ID          1000 non-null   str
 2   Duration             998 non-null    float64
 3   Representative       1000 non-null   str
 4   Date of Call         1000 non-null   datetime64[us]
 5   Purchase Amount      997 non-null    float64
 6   Satisfaction Rating  995 non-null    float64
dtypes: datetime64[us](1), float64(3), str(3)
memory usage: 54.8 KB

In [238]:
call.describe()

,Duration,Date of Call,Purchase Amount,Satisfaction Rating
count,998.000000,1000,997.000000,995.000000
mean,89.785571,2023-06-15 00:34:33.600000,96.755266,3.883920
min,2.000000,2023-01-01 00:00:00,20.000000,0.000000
25%,62.000000,2023-03-20 00:00:00,52.000000,3.400000
50%,89.000000,2023-05-25 12:00:00,88.000000,4.000000
75%,118.750000,2023-09-24 00:00:00,130.000000,4.500000
max,176.000000,2023-12-31 00:00:00,225.000000,5.000000
std,37.635907,NaN,52.445059,0.836469



1.total call
2.peak month
3.best representative
4.average duration of call
5.purchase amount
6.busy day
7.customer gender,city wise,,age wise

In [239]:
call.isnull()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False
4,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False

In [240]:
call.isnull().sum()

Call number            0
Customer ID            0
Duration               2
Representative         0
Date of Call           0
Purchase Amount        3
Satisfaction Rating    5
dtype: int64

In [241]:
customers.isnull().sum()

Customer ID.1    0
Gedner           0
Age              0
City             0
dtype: int64

In [242]:
call.isnull().any()  #any denotes any null in the column

Call number            False
Customer ID            False
Duration                True
Representative         False
Date of Call           False
Purchase Amount         True
Satisfaction Rating     True
dtype: bool

In [243]:
call.isnull().any(axis=0)  #axis = o is the column

Call number            False
Customer ID            False
Duration                True
Representative         False
Date of Call           False
Purchase Amount         True
Satisfaction Rating     True
dtype: bool

In [244]:
call.isnull().any(axis=1) #axis =1 denotes row

0       True
1      False
2      False
3       True
4       True
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [245]:
call.isnull().all() #all denotes entire column

Call number            False
Customer ID            False
Duration               False
Representative         False
Date of Call           False
Purchase Amount        False
Satisfaction Rating    False
dtype: bool

In [246]:

call[call.isnull().any(axis=1)]

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,Call_7271,C0003,NaN,R05,2023-01-01,128.0,4.9
3,Call_7274,C0014,119.0,R02,2023-01-01,NaN,2.9
4,Call_7275,C0011,NaN,R01,2023-01-02,31.0,2.8
12,Call_7283,C0002,98.0,R02,2023-01-04,NaN,3.5
17,Call_7288,C0009,28.0,R03,2023-01-05,NaN,3.8
24,Call_7295,C0010,54.0,R01,2023-01-08,111.0,NaN
29,Call_7300,C0015,155.0,R01,2023-01-10,110.0,NaN
46,Call_7317,C0014,131.0,R01,2023-01-19,78.0,NaN
51,Call_7322,C0013,100.0,R04,2023-01-21,135.0,NaN
54,Call_7325,C0013,59.0,R05,2023-01-22,136.0,NaN

In [247]:
call["Purchase Amount"].fillna(call["Purchase Amount"].mean(),inplace=True)

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_12728\65082465.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  call["Purchase Amount"].fillna(call["Purchase Amount"].mean(),inplace=True)

0      128.000000
1      135.000000
2       66.000000
3       96.755266
4       31.000000
          ...
995     28.000000
996    215.000000
997    115.000000
998     64.000000
999     40.000000
Name: Purchase Amount, Length: 1000, dtype: float64

In [248]:
call['Representative']=call['Representative'].fillna("unknown",inplace=True)

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_12728\856888587.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  call['Representative']=call['Representative'].fillna("unknown",inplace=True)

In [249]:
call.duplicated().sum()

np.int64(0)

In [250]:
call.drop_duplicates().all(axis=1)

0      True
1      True
2      True
3      True
4      True
       ...
995    True
996    True
997    True
998    True
999    True
Length: 1000, dtype: bool

In [251]:
call.drop_duplicates().all(axis=1).sum()

np.int64(999)

In [252]:
call.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call number          1000 non-null   str
 1   Customer ID          1000 non-null   str
 2   Duration             998 non-null    float64
 3   Representative       1000 non-null   str
 4   Date of Call         1000 non-null   datetime64[us]
 5   Purchase Amount      997 non-null    float64
 6   Satisfaction Rating  995 non-null    float64
dtypes: datetime64[us](1), float64(3), str(3)
memory usage: 54.8 KB

In [253]:
call.drop_duplicates(inplace=True)

In [254]:
call['Date of Call']=pd.to_datetime(call['Date of Call'])

In [255]:
call.dtypes

Call number                       str
Customer ID                       str
Duration                      float64
Representative                    str
Date of Call           datetime64[us]
Purchase Amount               float64
Satisfaction Rating           float64
dtype: object

In [256]:
call.rename(columns={'Purchase Amount':"Amount","Satisfaction Rating":"Rating"},inplace=True)

In [257]:
call.to_csv("Cleaned_data1.csv",index=False)

In [258]:
call[['Amount','Representative','Duration','Rating']]

     Amount Representative  Duration  Rating
0     128.0            R05       NaN     4.9
1     135.0            R05     119.0     2.9
2      66.0            R02      68.0     4.7
3       NaN            R02     119.0     2.9
4      31.0            R01       NaN     2.8
..      ...            ...       ...     ...
995    28.0            R05      81.0     3.9
996   215.0            R04     127.0     3.8
997   115.0            R05     146.0     2.3
998    64.0            R05     123.0     3.7
999    40.0            R01     114.0     3.9

[1000 rows x 4 columns]

In [260]:
type(call['Customer ID'])

pandas.Series

In [261]:
call.Rating.sort_values(ascending=False)

20     5.0
39     5.0
337    5.0
921    5.0
940    5.0
      ...
24     NaN
29     NaN
46     NaN
51     NaN
54     NaN
Name: Rating, Length: 1000, dtype: float64

In [262]:
call.Representative.unique()

<StringArray>
['R05', 'R02', 'R01', 'R04', 'R03']
Length: 5, dtype: str

In [264]:
customers.City.unique()

<StringArray>
['Columbus', 'Cleveland', 'Cincinnati']
Length: 3, dtype: str

In [267]:
repcount=call.Representative.value_counts()
repcount.max()

np.int64(218)

In [269]:
rep_count=call.groupby('Representative')['Rating'].mean()
print(rep_count)

Representative
R01    3.918817
R02    3.870642
R03    3.858937
R04    3.897838
R05    3.878894
Name: Rating, dtype: float64

In [271]:
high=call.groupby('Representative')['Call number'].count()
high.max()

np.int64(218)

In [274]:
merge_table=pd.merge(call,customers,left_on='Customer ID',right_on='Customer ID.1')
print(merge_table)

    Call number Customer ID  Duration Representative Date of Call  Amount  \
0     Call_7271       C0003       NaN            R05   2023-01-01   128.0
1     Call_7272       C0004     119.0            R05   2023-01-01   135.0
2     Call_7273       C0005      68.0            R02   2023-01-01    66.0
3     Call_7274       C0014     119.0            R02   2023-01-01     NaN
4     Call_7275       C0011       NaN            R01   2023-01-02    31.0
..          ...         ...       ...            ...          ...     ...
995   Call_8266       C0002      81.0            R05   2023-12-30    28.0
996   Call_8267       C0007     127.0            R04   2023-12-30   215.0
997   Call_8268       C0013     146.0            R05   2023-12-31   115.0
998   Call_8269       C0010     123.0            R05   2023-12-31    64.0
999   Call_8270       C0009     114.0            R01   2023-12-31    40.0

     Rating Customer ID.1  Gedner  Age        City
0       4.9         C0003    Male   26  Cincinnati
1       2.9         C0004    Male   36  Cincinnati
2       4.7         C0005    Male   37    Columbus
3       2.9         C0014  Female   38    Columbus
4       2.8         C0011  Female   30  Cincinnati
..      ...           ...     ...  ...         ...
995     3.9         C0002    Male   31   Cleveland
996     3.8         C0007  Female   22   Cleveland
997     2.3         C0013  Female   37   Cleveland
998     3.7         C0010  Female   30   Cleveland
999     3.9         C0009  Female   25    Columbus

[1000 rows x 11 columns]

In [273]:
call.shape

(1000, 7)

In [275]:
call.dtypes
customers.dtypes

Customer ID.1      str
Gedner             str
Age              int64
City               str
dtype: object

In [279]:
merge_table.groupby("City")["Amount"].sum()

City
Cincinnati    26061.0
Cleveland     37741.0
Columbus      32663.0
Name: Amount, dtype: float64